"""empty message

Revision ID: fb1c7579ba62
Revises: 5adba6a9a02b
Create Date: 2021-03-15 19:35:34.852833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1c7579ba62'
down_revision = '5adba6a9a02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('actor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'movies', 'actors', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'actor_id')
    # ### end Alembic commands ###
